### ISSUE TITLE
请问你是全新安装的11.1还是从10.15升级的？

### ISSUE THREAD

**Issue by michael-kj** [chinalichen/ASRock_Z390M_ITX_Clover_EFI#1]
请问你是全新安装的11.1还是从10.15升级的？

**Comment by chinalichen** [comment]
> 请问你是全新安装的11.1还是从10.15升级的？

我从10.15升级11.1失败了。
11.1建议使用OpenCore的方式全新安装，别用Clover的EFI。
改天我会上传基于这个硬件的OpenCore EFI，比clover好很多。

**Comment by michael-kj** [comment]
谢谢  期待你上传oc 的EFI
问一下  你全新安装11.1的时候  通过time machine 能恢复多少？比如一些bash，vim设置这种能恢复么

**Comment by chinalichen** [comment]
> 谢谢 期待你上传oc 的EFI
> 问一下 你全新安装11.1的时候 通过time machine 能恢复多少？比如一些bash，vim设置这种能恢复么

11.1的OC EFI，记得自己生成SMBIOS信息。全新安装，没有用到time machine，bash什么的从头设置了一遍😭。
https://github.com/chinalichen/ASRock_Z390M_ITX_OC_EFI
